#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1

traits:
    - securedBySteroidsApiKey:
        headers:
          steroidsApiKey:
            type: string
            example: exampleapikey
            default: 395e6d482fa3d311bd5b0458f3f0b278e9e2124431349b09d90c7f24aec5c6e4
          steroidsAppId:
            type: integer
            example: 1234
            default: 113204
  
schemas:
  - Attendees_collection: '{"$schema":"http://json-schema.org/schema","title":"Attendees collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Attendees representation","properties":{"Name":{"type":"string"},"Company":{"type":"string"},"Title":{"type":"string"},"LinkedIn URL":{"type":"string"},"Image URL":{"type":"string"}},"required":[]}}}}'
  - Attendees_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Attendees representation","properties":{"object":{"type":"object","properties":{"Name":{"type":"string"},"Company":{"type":"string"},"Title":{"type":"string"},"LinkedIn URL":{"type":"string"},"Image URL":{"type":"string"}},"required":[]}}}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/Attendees:
  description: |
    {
      "resourceName": "Attendees",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member


